# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: yulesong 's Home
subtitle: 生活不苟且
description: 原谅不美好,忘掉小烦恼
keywords:
author: yule song
language: zh-Hans
timezone:

# 侧边栏头像设置
avatar: /img/pikaqiu.jpg 

# Local Search  添加本地搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:


# Feed 订阅
feed: # 需安装插件：npm install hexo-generator-feed --save
  type: atom
  path: atom.xml
  limit: 20
  hub:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
plugins: 
  hexo-generate-feed
  hexo-algoliasearch
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git 
  repository: git@github.com:yulesong/yulesong.github.io.git
  branch: master





